repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks: []

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks: []

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks: []

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks: []

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks: []

  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks: []

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks: []

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks: []

  # Local hooks disabled
  # - repo: local
  #     hooks:
  #       - id: pytest-check         # Disabled to ignore pytest errors
  #       - id: security-check       # Disabled to ignore safety errors
